checkInterval: 60  # In ticks (20 ticks = 1 second)
movementDistance: 2 # Amount of blocks a player needs to move to be counted as not afk
checksBeforeAfk: 5 # Amount of checks a person needs to not have moved enough to be AFK
enableAfkCommand: true # Reloading the plugin WILL NOT disable this command, you need to reload the whole server for this to disable!

messages:
  prefix: '&aAFK: &7'
  insufficientPermissions: '%afk_prefix%Insufficient Permissions.'
  invalidUsage: '%afk_prefix%Invalid Usage.'
  reloading: '%afk_prefix%Reloading...'
  reloaded: '%afk_prefix%Reloaded.'
  mustBeAPlayer: '%afk_prefix%You must be a player to use this command.'
  afkAreaSet: '%afk_prefix%AFK Area set successfully.'
  playerIsInvincible: '%afk_prefix%%player_name% is currently AFK and therefore invincible.'

  isAfk:
    unknown: "%afk_prefix%Unknown Username or UUID. (Players must be online)."
    notEnoughArgs: "%afk_prefix%Not enough arguments provided. Usage /isafk <username/uuid>"
    afk: "%afk_prefix%%player_name% is currently AFK."
    notAfk: "%afk_prefix%%player_name% is currently active."

  afkList:
    listPrefix: "%afk_prefix%The following players are currently AFK: "
    inventoryTitle: "&7Currently AFK Players."

# If the user has the permission afk.groups.donator then they will inherit the settings from the donator rank.
# Ranks at the top of the list have the highest priority
groups:
  donator:
    checkAmount: 200

detection:
  gamemodes:
    survival: true
    adventure: true
    creative: false # This will disable players from going afk if they are in this gamemode
    spectator: false

  # If an event is enabled then the checks for the player are reset.
  # These events firing WILL NOT cause a script to run.
  events:
    blockBreakEvent: true
    blockPlaceEvent: true
    chatEvent: true


  fishing:
    enabled: true
    violationsNeeded: 5

  operatorsExempt: true # Players who have the permission afk.exempt but aren't OP will still be exempt

scripts:
  onAfk:
    - action: "afkarea"

    - action: "message"
      content: "&cNow AFK"
      repeat: 2

    - action: "title"
      title: "&c&lAFK"
      subtitle: "&7See you soon!"
      fadeIn: 10
      fadeOut: 10
      stay: "permanent"

    - action: "actionbar"
      content: "&c&lAFK."
      to: "player"
      permanent: true

  onReturn:
    - action: "afkarea"

    - action: "message"
      content: "&cNo longer AFK"

    - action: "title"
      title: "&a&lWelcome Back!"
      fadeIn: 10
      fadeOut: 10
      stay: 20

    - action: "actionbar"
      reset: true

    - action: "actionbar"
      content: "&a&lWelcome Back."

  onAfkDisconnect: # Some actions may not work as the player is technically destroyed by this point.
    - action: "command"
      by: "console"
      command: "afk help"

  onAfkCMD:
    - action: "afkarea"

    - action: "message"
      content: "&bAFK by command."

  onReturnCMD:
    - action: "afkarea"

    - action: "message"
      content: "&bReturn by command."

  onFishingAFK:
    - action: "look"
      pitch: 100

    - action: "message"
      content: "&cAFK Fishing isn't allowed."

